import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Provider from "@/components/provider";
import { getServerSession } from "next-auth";
import { options } from "@/lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>
          <Header />
        </Provider>
        <main>
          {children}
        </main>
        </body>
    </html>
  );
}
